### ISSUE TITLE
CR 5: There is no function to automatically calculate and increase the age each year automatically

### ISSUE THREAD

**Issue by syah769** [syah769/E-KhairatSCM#6]
The staff has to manually enter the members' ages during registration and manually keep track of their ages as they increase each year. It would be more efficient if the ages could be automatically updated based on the current date, rather than relying on manual input from the staff.

**Comment by ShahSavier** [comment]
already fix this part by adding [ $kariah_umur = date('Y-m-d', strtotime($_POST['kariah_umur'])); ] on daftar-ahli-kariah.php
